PRODUCT_PATH = "/product/"
PART_LIST_PATH = "/list/"
SEARCH_PATH = "/search/"
PART_REVIEWS_PATH = "/reviews/"
PRODUCTS_PATH = "/products/"


PRODUCT_KEYBOARD_PATH = "keyboard"
PRODUCT_SPEAKERS_PATH = "speakers"
PRODUCT_MONITOR_PATH = "monitor"
PRODUCT_THERMAL_PASTE_PATH = "thermal-paste"
PRODUCT_VIDEO_CARD_PATH = "video-card"
PRODUCT_CASE_FAN_PATH = "case-fan"
PRODUCT_OS_PATH = "os"
PRODUCT_CPU_COOLER_PATH = "cpu-cooler"
PRODUCT_FAN_CONTROLLER_PATH = "fan-controller"
PRODUCT_UPS_PATH = "ups"
PRODUCT_WIRED_NETWORK_CARD_PATH = "wired-network-card"
PRODUCT_MEMORY_PATH = "memory"
PRODUCT_HEADPHONES_PATH = "headphones"
PRODUCT_SOUND_CARD_PATH = "sound-card"
PRODUCT_INTERNAL_HARD_DRIVE_PATH = "internal-hard-drive"
PRODUCT_MOUSE_PATH = "mouse"
PRODUCT_WIRELESS_NETWORK_CARD_PATH = "wireless-network-card"
PRODUCT_POWER_SUPPLY_PATH = "power-supply"
PRODUCT_WEBCAM_PATH = "webcam"
PRODUCT_MOTHERBOARD_PATH = "motherboard"
PRODUCT_EXTERNAL_HARD_DRIVE_PATH = "external-hard-drive"
PRODUCT_OPTICAL_DRIVE_PATH = "optical-drive"
PRODUCT_CASE_PATH = "case"
PRODUCT_CPU_PATH = "cpu"

PRODUCT_PATHS = (
    PRODUCT_KEYBOARD_PATH,
    PRODUCT_SPEAKERS_PATH,
    PRODUCT_MONITOR_PATH,
    PRODUCT_THERMAL_PASTE_PATH,
    PRODUCT_VIDEO_CARD_PATH,
    PRODUCT_CASE_FAN_PATH,
    PRODUCT_OS_PATH,
    PRODUCT_CPU_COOLER_PATH,
    PRODUCT_FAN_CONTROLLER_PATH,
    PRODUCT_UPS_PATH,
    PRODUCT_WIRED_NETWORK_CARD_PATH,
    PRODUCT_MEMORY_PATH,
    PRODUCT_HEADPHONES_PATH,
    PRODUCT_SOUND_CARD_PATH,
    PRODUCT_INTERNAL_HARD_DRIVE_PATH,
    PRODUCT_MOUSE_PATH,
    PRODUCT_WIRELESS_NETWORK_CARD_PATH,
    PRODUCT_POWER_SUPPLY_PATH,
    PRODUCT_WEBCAM_PATH,
    PRODUCT_MOTHERBOARD_PATH,
    PRODUCT_EXTERNAL_HARD_DRIVE_PATH,
    PRODUCT_OPTICAL_DRIVE_PATH,
    PRODUCT_CASE_PATH,
    PRODUCT_CPU_PATH,
)
